# Values for terratest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: uclalibrary/terra
  tag: v1.1.6
  pullPolicy: Always

nameOverride: ""

fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: "true"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: sectigo-acme-clusterissuer
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: 'terra.library.ucla.edu'
      paths:
        - "/"
  tls:
  - secretName: prod-terra-tls
    hosts:
      - terra.library.ucla.edu

django:
  env:
    run_env: "prod"
    debug: "false"
    log_level: "INFO"
    allowed_hosts:
      - terra.library.ucla.edu
    csrf_trusted_origins:
      - https://terra.library.ucla.edu
    db_backend: "django.db.backends.postgresql"
    db_name: "terraprod"
    db_user: "terraprod"
    db_host: "p-d-postgres.library.ucla.edu"
    db_port: 5432
    test_db_name: "test_terra"
    email_host: "smtp.ucla.edu"

  externalSecrets:
    enabled: "true"
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
    env:
      db_password: "/systems/prodrke01/terra/db_password"
      django_secret_key: "/systems/prodrke01/terra/django_secret_key"

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
