# Generated by Django 2.2.4 on 2019-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("terra", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="uid",
            field=models.CharField(default="INVALID", max_length=9, unique=True),
            preserve_default=False,
        )
    ]
