# Generated by Django 2.2.3 on 2019-08-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("terra", "0002_employee_uid")]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="terra.Employee",
            ),
        )
    ]
