# Generated by Django 2.2.5 on 2019-09-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0002_vacation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
