# Generated by Django 2.2.5 on 2019-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0003_auto_20190926_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
