# Generated by Django 2.2.3 on 2019-09-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("terra", "0004_auto_20190904_2316")]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="parent_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subunits",
                to="terra.Unit",
            ),
        )
    ]
