# Generated by Django 2.2.4 on 2019-10-07 17:10

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0004_auto_20190927_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name', '-end'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': [django.db.models.expressions.F('user__last_name'), django.db.models.expressions.F('user__first_name')]},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['account', 'cost_center', 'fund']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='allocationexpires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='extraallocation',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
