# Generated by Django 2.2.5 on 2019-09-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0005_auto_20190906_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('EXEC', 'Executive'), ('HEAD', 'Unit Head'), ('LIBR', 'Librarian'), ('SENR', 'Sr. Exempt Staff'), ('OTHR', 'Other')], default='OTHR', max_length=4),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('1', 'Library'), ('2', 'Executive Division'), ('3', 'Managerial Unit')], max_length=1),
        ),
    ]
