# Generated by Django 2.2.5 on 2019-10-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("terra", "0006_auto_20191010_1622")]

    operations = [
        migrations.RemoveField(model_name="approval", name="note"),
        migrations.RemoveField(model_name="travelrequest", name="note"),
        migrations.AddField(
            model_name="fund",
            name="unit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="terra.Unit"
            ),
        ),
    ]
