# Generated by Django 2.2.5 on 2019-10-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0006_fund_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
