# Generated by Django 2.2.9 on 2020-01-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0007_auto_20191010_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('ULBR', 'University Librarian'), ('EXEC', 'Executive'), ('HEAD', 'Unit Head'), ('LIBR', 'Librarian'), ('SENR', 'Sr. Exempt Staff'), ('OTHR', 'Other')], default='OTHR', max_length=4),
        ),
    ]
