# Generated by Django 2.2.9 on 2020-01-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0008_auto_20200106_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approval',
            new_name='Funding',
        ),
    ]
