# Generated by Django 2.2.9 on 2020-01-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0010_auto_20200108_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funding',
            options={'verbose_name_plural': 'Funding'},
        ),
    ]
