# Generated by Django 2.2.8 on 2020-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0011_auto_20200108_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualexpense',
            name='date_paid',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
