# Generated by Django 2.2.5 on 2020-02-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("terra", "0013_actualexpense_reimbursed")]

    operations = [migrations.DeleteModel(name="EstimatedExpense")]
