# Generated by Django 2.2.10 on 2020-03-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("terra", "0014_delete_estimatedexpense")]

    operations = [
        migrations.AddField(
            model_name="travelrequest",
            name="canceled",
            field=models.BooleanField(default=False),
        )
    ]
